module Rafsi (rafsiFor) where

import qualified Data.Map.Strict as M
import Data.Map.Strict (Map)
import Lojban

rafsiFor :: Valsi -> [Rafsi]
rafsiFor v = shortRafsi ++ longRafsi
  where
    shortRafsi = M.findWithDefault [] v rafsiMap
    longRafsi = if length v == 5 then [take 4 v, v] else []

rafsiMap :: Map Gismu [Rafsi]
rafsiMap =
  M.fromList
    [ ("bacru", ["ba'u"])
    , ("badri", ["dri"])
    , ("bajra", ["baj"])
    , ("bakfu", ["baf"])
    , ("bakni", ["bak"])
    , ("balre", ["ba'e"])
    , ("balvi", ["bav"])
    , ("bancu", ["bac"])
    , ("bandu", ["bad"])
    , ("bangu", ["ban", "bau"])
    , ("banli", ["ba'i", "bal"])
    , ("banro", ["ba'o"])
    , ("banxa", ["bax"])
    , ("banzu", ["baz"])
    , ("bapli", ["bai", "bap"])
    , ("barda", ["bra"])
    , ("bargu", ["bag"])
    , ("barna", ["ba'a"])
    , ("bartu", ["bar"])
    , ("basti", ["bas"])
    , ("batci", ["bat"])
    , ("bebna", ["beb"])
    , ("bemro", ["be'o", "bem"])
    , ("bende", ["be'e", "bed"])
    , ("bengo", ["beg"])
    , ("benji", ["be'i", "bej"])
    , ("bersa", ["be'a", "bes"])
    , ("berti", ["ber"])
    , ("besna", ["ben"])
    , ("betfu", ["be'u", "bef"])
    , ("betri", ["bet"])
    , ("bevri", ["bei", "bev"])
    , ("bi",    ["biv"])
    , ("bi'i",  ["biz"])
    , ("bifce", ["bic"])
    , ("bikla", ["bik"])
    , ("bilga", ["big"])
    , ("bilma", ["bi'a"])
    , ("bilni", ["bil"])
    , ("bindo", ["bid"])
    , ("binxo", ["bi'o", "bix"])
    , ("birka", ["bir"])
    , ("birti", ["bit"])
    , ("bisli", ["bis"])
    , ("bitmu", ["bi'u", "bim"])
    , ("blabi", ["lab"])
    , ("blanu", ["bla"])
    , ("bliku", ["bli"])
    , ("bloti", ["blo", "lo'i", "lot"])
    , ("bo",    ["bor"])
    , ("bolci", ["boi", "bol"])
    , ("bongu", ["bo'u", "bog"])
    , ("botpi", ["bo'i", "bot"])
    , ("boxfo", ["bo'o", "bof"])
    , ("boxna", ["bo'a", "bon"])
    , ("brazo", ["raz"])
    , ("bredi", ["bre", "red"])
    , ("bridi", ["bri"])
    , ("brife", ["bi'e", "bif"])
    , ("briju", ["bij"])
    , ("brito", ["rit"])
    , ("broda", ["rod"])
    , ("brode", ["bo'e"])
    , ("bruna", ["bu'a", "bun"])
    , ("bu",    ["bu'i", "bus"])
    , ("bu'a",  ["bul"])
    , ("budjo", ["bu'o", "buj"])
    , ("bukpu", ["bu'u", "buk"])
    , ("bumru", ["bum"])
    , ("bunda", ["bud"])
    , ("bunre", ["bu'e", "bur"])
    , ("burcu", ["bru"])
    , ("ca'a",  ["caz"])
    , ("cabna", ["cab"])
    , ("cabra", ["ca'a"])
    , ("cadzu", ["dzu"])
    , ("cafne", ["caf"])
    , ("calku", ["cak"])
    , ("cando", ["cad"])
    , ("cange", ["cag"])
    , ("canja", ["caj"])
    , ("canko", ["ca'o"])
    , ("canlu", ["ca'u", "cal"])
    , ("canpa", ["cna"])
    , ("canre", ["can"])
    , ("carmi", ["cai", "cam"])
    , ("carna", ["car"])
    , ("cartu", ["cat"])
    , ("carvi", ["cav"])
    , ("casnu", ["snu"])
    , ("catke", ["ca'e"])
    , ("catlu", ["cta"])
    , ("catni", ["ca'i"])
    , ("caxno", ["cax"])
    , ("ce",    ["cec"])
    , ("ce'i",  ["cez"])
    , ("ce'o",  ["ce'o"])
    , ("cecla", ["ce'a", "cel"])
    , ("cecmu", ["ce'u", "cem"])
    , ("cenba", ["cne"])
    , ("censa", ["ces"])
    , ("centi", ["cen"])
    , ("cerda", ["ced"])
    , ("cerni", ["cer"])
    , ("certu", ["cre"])
    , ("cevni", ["cei", "cev"])
    , ("cfari", ["cfa"])
    , ("cfika", ["fi'a", "fik"])
    , ("cfila", ["cfi"])
    , ("cfipu", ["fi'u"])
    , ("ci",    ["cib"])
    , ("ciblu", ["blu"])
    , ("cidja", ["dja"])
    , ("cidni", ["cid"])
    , ("cidro", ["dro"])
    , ("cifnu", ["cif"])
    , ("cigla", ["cig"])
    , ("cikna", ["cik"])
    , ("ciksi", ["cki"])
    , ("cilce", ["cic"])
    , ("cilmo", ["cim"])
    , ("cilre", ["cli"])
    , ("cilta", ["cil"])
    , ("cinje", ["cij"])
    , ("cinmo", ["cni"])
    , ("cinri", ["ci'i"])
    , ("cinse", ["cin"])
    , ("cipni", ["cpi"])
    , ("cipra", ["cip"])
    , ("cirko", ["cri"])
    , ("ciska", ["ci'a"])
    , ("ciste", ["ci'e"])
    , ("citka", ["cti"])
    , ("citno", ["ci'o", "cit"])
    , ("citri", ["cir"])
    , ("civla", ["civ"])
    , ("cizra", ["ciz"])
    , ("ckafi", ["kaf"])
    , ("ckaji", ["kai"])
    , ("ckana", ["cka"])
    , ("ckape", ["cap"])
    , ("ckasu", ["cas"])
    , ("ckeji", ["cke", "kej"])
    , ("ckiku", ["kik"])
    , ("ckilu", ["ci'u"])
    , ("ckini", ["ki'i"])
    , ("ckire", ["kir"])
    , ("ckule", ["cu'e", "kul"])
    , ("ckunu", ["ku'u"])
    , ("cladu", ["lau"])
    , ("clani", ["cla"])
    , ("claxu", ["cau"])
    , ("clira", ["lir"])
    , ("clite", ["lit"])
    , ("cliva", ["li'a", "liv"])
    , ("clupa", ["cup"])
    , ("cmalu", ["cma"])
    , ("cmana", ["ma'a"])
    , ("cmavo", ["ma'o"])
    , ("cmene", ["cme", "me'e"])
    , ("cmila", ["mi'a"])
    , ("cmima", ["cmi", "mim"])
    , ("cmoni", ["cmo", "co'i"])
    , ("cnano", ["na'o"])
    , ("cnebo", ["ne'o", "neb"])
    , ("cnemu", ["ne'u", "nem"])
    , ("cnici", ["nic"])
    , ("cnino", ["ni'o", "nin"])
    , ("cnisa", ["nis"])
    , ("cnita", ["ni'a", "nit"])
    , ("co",    ["col"])
    , ("co'a",  ["co'a"])
    , ("co'e",  ["co'e", "com"])
    , ("co'u",  ["co'u"])
    , ("cokcu", ["cko"])
    , ("condi", ["cno", "coi", "con"])
    , ("cortu", ["cor", "cro"])
    , ("cpacu", ["cpa"])
    , ("cpare", ["par"])
    , ("cpedu", ["cpe"])
    , ("crane", ["cra"])
    , ("creka", ["cek"])
    , ("crepu", ["rep"])
    , ("cribe", ["rib"])
    , ("crida", ["rid"])
    , ("crino", ["ri'o"])
    , ("cripu", ["rip"])
    , ("crisa", ["cis"])
    , ("ctebi", ["teb"])
    , ("cteki", ["ce'i", "tek"])
    , ("ctino", ["ti'o"])
    , ("ctuca", ["ctu"])
    , ("cukla", ["cuk"])
    , ("cukta", ["cku"])
    , ("culno", ["clu"])
    , ("cumki", ["cu'i", "cum"])
    , ("cumla", ["cul"])
    , ("cunso", ["cu'o", "cun"])
    , ("cuntu", ["cu'u"])
    , ("cupra", ["pra"])
    , ("curmi", ["cru"])
    , ("curnu", ["cur"])
    , ("curve", ["cuv"])
    , ("cusku", ["cus", "sku"])
    , ("cutci", ["cuc"])
    , ("cutne", ["cut"])
    , ("cuxna", ["cu'a", "cux"])
    , ("da",    ["dav", "dza"])
    , ("da'a",  ["daz"])
    , ("dacru", ["dac"])
    , ("dacti", ["dai"])
    , ("dadjo", ["daj"])
    , ("dakfu", ["dak"])
    , ("damba", ["da'a", "dab"])
    , ("dandu", ["dad"])
    , ("danfu", ["daf"])
    , ("danlu", ["da'u", "dal"])
    , ("danmo", ["dam"])
    , ("danre", ["da'e"])
    , ("danti", ["dan"])
    , ("daplu", ["plu"])
    , ("dapma", ["dap"])
    , ("dargu", ["dag"])
    , ("darlu", ["dau"])
    , ("darno", ["da'o", "dar"])
    , ("darxi", ["da'i", "dax"])
    , ("dasni", ["das"])
    , ("daspo", ["spo"])
    , ("dasri", ["sri"])
    , ("decti", ["dec"])
    , ("degji", ["deg"])
    , ("dejni", ["dej"])
    , ("dekto", ["dek"])
    , ("delno", ["de'o", "del"])
    , ("dembi", ["deb"])
    , ("denci", ["de'i", "den"])
    , ("denmi", ["dem"])
    , ("denpa", ["de'a", "dep"])
    , ("dertu", ["de'u", "der"])
    , ("derxi", ["dre"])
    , ("desku", ["des"])
    , ("detri", ["det"])
    , ("dicra", ["dir"])
    , ("dikca", ["dic"])
    , ("diklo", ["klo"])
    , ("dikni", ["dik"])
    , ("dilnu", ["dil"])
    , ("dimna", ["dim"])
    , ("dinju", ["di'u", "dij"])
    , ("dinko", ["di'o"])
    , ("dirba", ["dib"])
    , ("dirce", ["di'e"])
    , ("dirgo", ["dig"])
    , ("dizlo", ["diz", "dzi"])
    , ("djacu", ["jac", "jau"])
    , ("djedi", ["dei", "dje"])
    , ("djica", ["dji"])
    , ("djine", ["jin"])
    , ("djuno", ["ju'o", "jun"])
    , ("do",    ["doi", "don"])
    , ("donri", ["do'i", "dor"])
    , ("dotco", ["do'o", "dot"])
    , ("drani", ["dra"])
    , ("drata", ["dat"])
    , ("drudi", ["dru", "rud"])
    , ("du",    ["du'o", "dub"])
    , ("du'u",  ["dum"])
    , ("dugri", ["dug"])
    , ("dukse", ["du'e", "dus"])
    , ("dukti", ["dut"])
    , ("dunda", ["du'a", "dud"])
    , ("dunja", ["duj"])
    , ("dunku", ["du'u", "duk"])
    , ("dunli", ["du'i", "dun"])
    , ("dunra", ["dur"])
    , ("dzena", ["dze"])
    , ("dzipo", ["zi'o", "zip"])
    , ("facki", ["fa'i", "fak"])
    , ("fadni", ["fad"])
    , ("fagri", ["fag"])
    , ("falnu", ["fan"])
    , ("fanmo", ["fa'o", "fam"])
    , ("fanza", ["faz"])
    , ("fapro", ["fap", "pro"])
    , ("farlu", ["fa'u", "fal"])
    , ("farna", ["fa'a", "far"])
    , ("farvi", ["fav"])
    , ("fasnu", ["fau"])
    , ("fatci", ["fac"])
    , ("fatne", ["fa'e", "fat"])
    , ("fatri", ["fai"])
    , ("febvi", ["feb"])
    , ("femti", ["fem"])
    , ("fendi", ["fed"])
    , ("fengu", ["fe'u", "feg"])
    , ("fenki", ["fek"])
    , ("fenra", ["fe'a", "fer"])
    , ("fenso", ["fe'o", "fen"])
    , ("fepni", ["fei", "fep"])
    , ("ferti", ["fre"])
    , ("festi", ["fes"])
    , ("fetsi", ["fe'i", "fet"])
    , ("figre", ["fig"])
    , ("filso", ["fis"])
    , ("finpe", ["fi'e", "fip"])
    , ("finti", ["fi'i", "fin"])
    , ("flalu", ["fla"])
    , ("flecu", ["fle"])
    , ("fliba", ["fli"])
    , ("flira", ["fir"])
    , ("fo'a",  ["fo'a"])
    , ("fo'e",  ["fo'e"])
    , ("fo'i",  ["fo'i"])
    , ("foldi", ["flo", "foi"])
    , ("fonmo", ["fo'o", "fom"])
    , ("fonxa", ["fon"])
    , ("forca", ["fro"])
    , ("fraso", ["fas"])
    , ("frati", ["fra"])
    , ("fraxu", ["fax"])
    , ("frica", ["fic"])
    , ("friko", ["fi'o"])
    , ("frili", ["fil"])
    , ("friti", ["fit"])
    , ("frumu", ["fru"])
    , ("fukpi", ["fu'i", "fuk"])
    , ("fulta", ["flu", "ful"])
    , ("funca", ["fu'a", "fun"])
    , ("fusra", ["fur"])
    , ("fuzme", ["fu'e", "fuz"])
    , ("gacri", ["gai"])
    , ("gadri", ["gad"])
    , ("galfi", ["ga'i", "gaf"])
    , ("galtu", ["ga'u", "gal"])
    , ("ganlo", ["ga'o"])
    , ("ganra", ["gan"])
    , ("ganse", ["ga'e", "gas"])
    , ("ganxo", ["gax"])
    , ("ganzu", ["gaz"])
    , ("gapci", ["gac"])
    , ("gapru", ["gap"])
    , ("garna", ["gar"])
    , ("gasnu", ["gau"])
    , ("gasta", ["gat"])
    , ("genja", ["gej"])
    , ("gento", ["ge'o", "get"])
    , ("genxu", ["gex"])
    , ("gerku", ["ge'u", "ger"])
    , ("gerna", ["ge'a", "gen"])
    , ("gidva", ["gi'a", "gid"])
    , ("gigdo", ["gi'o", "gig"])
    , ("ginka", ["gik"])
    , ("girzu", ["gir", "gri"])
    , ("gismu", ["gi'u", "gim"])
    , ("glare", ["gla"])
    , ("gleki", ["gei", "gek"])
    , ("gletu", ["gle", "let"])
    , ("glico", ["gic", "gli"])
    , ("gluta", ["glu"])
    , ("gocti", ["goc"])
    , ("gotro", ["got"])
    , ("gradu", ["rau"])
    , ("grake", ["gra"])
    , ("grana", ["ga'a"])
    , ("grasu", ["ras"])
    , ("greku", ["rek"])
    , ("grusi", ["rus"])
    , ("grute", ["rut"])
    , ("gubni", ["gub"])
    , ("gugde", ["gu'e", "gug"])
    , ("gundi", ["gud"])
    , ("gunka", ["gu'a", "gun"])
    , ("gunma", ["gum"])
    , ("gunro", ["gu'o", "gur"])
    , ("gunta", ["gut"])
    , ("gurni", ["gru"])
    , ("guska", ["guk"])
    , ("gusni", ["gu'i", "gus"])
    , ("gutci", ["guc"])
    , ("guzme", ["guz", "zme"])
    , ("ja",    ["jav"])
    , ("jadni", ["ja'i", "jad"])
    , ("jalge", ["ja'e", "jag"])
    , ("jamfu", ["jaf", "jma"])
    , ("jamna", ["jam"])
    , ("janbe", ["jab"])
    , ("janco", ["jan"])
    , ("janli", ["jal"])
    , ("jansu", ["jas"])
    , ("janta", ["jat"])
    , ("jarco", ["ja'o"])
    , ("jarki", ["jak"])
    , ("jaspu", ["jap"])
    , ("jatna", ["ja'a"])
    , ("javni", ["jva"])
    , ("jbama", ["bam"])
    , ("jbari", ["jba"])
    , ("jbena", ["jbe"])
    , ("jbera", ["jer"])
    , ("jbini", ["bi'i", "bin"])
    , ("jdari", ["jar"])
    , ("jdice", ["jdi"])
    , ("jdima", ["di'a"])
    , ("jdini", ["di'i", "din"])
    , ("jduli", ["dul", "jdu"])
    , ("je",    ["jev", "jve"])
    , ("jecta", ["je'a", "jec"])
    , ("jeftu", ["jef"])
    , ("jegvo", ["je'o", "jeg"])
    , ("jei",   ["jez"])
    , ("jelca", ["jel"])
    , ("jemna", ["jme"])
    , ("jenca", ["jen"])
    , ("jendu", ["jed"])
    , ("jenmi", ["jei", "jem"])
    , ("jersi", ["je'i"])
    , ("jerxo", ["jex"])
    , ("jesni", ["jes"])
    , ("jetce", ["je'e"])
    , ("jetnu", ["je'u", "jet"])
    , ("jgalu", ["ja'u"])
    , ("jganu", ["jga"])
    , ("jgari", ["jai"])
    , ("jgena", ["jge"])
    , ("jgina", ["gin"])
    , ("jgira", ["jgi"])
    , ("jgita", ["git"])
    , ("jibni", ["jbi"])
    , ("jibri", ["jib"])
    , ("jicmu", ["cmu"])
    , ("jijnu", ["jij"])
    , ("jikca", ["jik"])
    , ("jilka", ["jil"])
    , ("jimca", ["jic"])
    , ("jimpe", ["jmi"])
    , ("jimte", ["jit"])
    , ("jinga", ["ji'a", "jig"])
    , ("jinme", ["jim"])
    , ("jinru", ["jir"])
    , ("jinsa", ["jis"])
    , ("jinvi", ["ji'i", "jiv"])
    , ("jinzi", ["jiz"])
    , ("jipno", ["ji'o", "jip"])
    , ("jitfa", ["jif"])
    , ("jitro", ["tro"])
    , ("jivna", ["jvi"])
    , ("jmaji", ["jaj"])
    , ("jmina", ["min"])
    , ("jmive", ["ji'e", "miv"])
    , ("jo",    ["jov"])
    , ("jo'e",  ["jom"])
    , ("jo'u",  ["jo'u"])
    , ("joi",   ["joi", "jol"])
    , ("jordo", ["jo'o", "jor"])
    , ("jorne", ["jo'e", "jon"])
    , ("ju",    ["juv"])
    , ("jubme", ["jbu", "jub"])
    , ("jufra", ["ju'a", "juf"])
    , ("jukni", ["juk"])
    , ("jukpa", ["jup"])
    , ("julne", ["ju'e"])
    , ("jundi", ["ju'i", "jud"])
    , ("jungo", ["jug"])
    , ("junla", ["jul"])
    , ("junri", ["jur"])
    , ("jurme", ["jum"])
    , ("jursa", ["jus"])
    , ("jutsi", ["jut"])
    , ("juxre", ["jux"])
    , ("jvinu", ["ji'u", "vin"])
    , ("ka",    ["kam"])
    , ("kagni", ["kag"])
    , ("kajde", ["jde"])
    , ("kakne", ["ka'e"])
    , ("kalri", ["kar"])
    , ("kalsa", ["kas"])
    , ("kalte", ["kat"])
    , ("kampu", ["kau"])
    , ("kancu", ["kac"])
    , ("kandi", ["kad"])
    , ("kanji", ["kaj"])
    , ("kanla", ["kal"])
    , ("kanro", ["ka'o"])
    , ("kansa", ["kan"])
    , ("kantu", ["ka'u"])
    , ("kanxe", ["kax"])
    , ("karbi", ["kab"])
    , ("katna", ["ka'a"])
    , ("kavbu", ["kav"])
    , ("ke",    ["kem"])
    , ("ke'e",  ["ke'e", "kep"])
    , ("kecti", ["ke'i", "kec"])
    , ("kei",   ["kez"])
    , ("kelci", ["kei", "kel"])
    , ("kelvo", ["ke'o"])
    , ("kenra", ["ken"])
    , ("kensa", ["kes"])
    , ("kerfa", ["kre"])
    , ("kerlo", ["ker"])
    , ("ketco", ["ket", "tco"])
    , ("kevna", ["ke'a", "kev"])
    , ("kicne", ["ki'e", "kic"])
    , ("kijno", ["kij"])
    , ("kilto", ["ki'o"])
    , ("kinli", ["kil"])
    , ("kisto", ["kis"])
    , ("klaji", ["laj"])
    , ("klaku", ["kak"])
    , ("klama", ["kla"])
    , ("klani", ["lai"])
    , ("klesi", ["kle", "lei"])
    , ("klina", ["kli"])
    , ("kliti", ["kit"])
    , ("klupe", ["lu'e", "lup"])
    , ("kluza", ["luz"])
    , ("kobli", ["ko'i", "kob"])
    , ("kojna", ["ko'a", "koj"])
    , ("kolme", ["ko'e", "kol"])
    , ("komcu", ["kom"])
    , ("konju", ["ko'u", "kon"])
    , ("korbi", ["koi", "kor"])
    , ("korcu", ["kro"])
    , ("korka", ["kok"])
    , ("kosta", ["kos"])
    , ("krasi", ["kra"])
    , ("krati", ["ka'i"])
    , ("krefu", ["ke'u", "ref"])
    , ("krici", ["kri"])
    , ("krinu", ["ki'u", "rin"])
    , ("krixa", ["ki'a", "kix"])
    , ("kruca", ["kuc"])
    , ("kruji", ["ruj"])
    , ("kruvi", ["kru", "ruv"])
    , ("ku'a",  ["kuz"])
    , ("kubli", ["kub"])
    , ("kufra", ["kuf"])
    , ("kukte", ["kuk"])
    , ("kulnu", ["klu"])
    , ("kumfa", ["ku'a", "kum"])
    , ("kunra", ["kun"])
    , ("kunti", ["kut"])
    , ("kurfa", ["kur"])
    , ("kurji", ["ku'i", "kuj"])
    , ("kuspe", ["ku'e", "kup"])
    , ("kusru", ["kus"])
    , ("lacpu", ["cpu", "lap"])
    , ("lacri", ["lac"])
    , ("ladru", ["lad"])
    , ("lafti", ["laf"])
    , ("lakne", ["la'e"])
    , ("lakse", ["lak"])
    , ("lalxu", ["la'u"])
    , ("lamji", ["la'i", "lam"])
    , ("lanli", ["lal"])
    , ("lanme", ["lan"])
    , ("lanxe", ["lax"])
    , ("lanzu", ["laz"])
    , ("larcu", ["lar"])
    , ("lasna", ["la'a"])
    , ("latmo", ["la'o"])
    , ("le'e",  ["lem"])
    , ("lebna", ["le'a", "leb"])
    , ("lenjo", ["le'o", "len"])
    , ("lenku", ["lek"])
    , ("lerci", ["lec"])
    , ("lerfu", ["le'u", "ler"])
    , ("li'i",  ["liz"])
    , ("libjo", ["lib"])
    , ("lidne", ["li'e"])
    , ("lifri", ["fri", "lif"])
    , ("lijda", ["jda"])
    , ("limna", ["lim"])
    , ("lindi", ["lid"])
    , ("linji", ["li'i", "lij"])
    , ("linsi", ["lin"])
    , ("linto", ["li'o"])
    , ("lisri", ["lis"])
    , ("liste", ["ste"])
    , ("litce", ["lic"])
    , ("litki", ["lik"])
    , ("litru", ["li'u"])
    , ("livla", ["lil"])
    , ("lo'e",  ["lom"])
    , ("logji", ["loj"])
    , ("lojbo", ["jbo", "lob"])
    , ("loldi", ["loi", "lol"])
    , ("lorxu", ["lo'u", "lor"])
    , ("lubno", ["lu'o"])
    , ("lujvo", ["jvo", "luv"])
    , ("lumci", ["lu'i", "lum"])
    , ("lunbe", ["lub"])
    , ("lunra", ["lur"])
    , ("lunsa", ["lus"])
    , ("mabla", ["mal"])
    , ("mabru", ["mab"])
    , ("macnu", ["cnu"])
    , ("makcu", ["ma'u"])
    , ("makfa", ["maf"])
    , ("maksi", ["mak"])
    , ("malsi", ["mas"])
    , ("mamta", ["mam"])
    , ("manci", ["mac"])
    , ("manku", ["man"])
    , ("manri", ["mar"])
    , ("mapku", ["map"])
    , ("mapti", ["mat"])
    , ("marbi", ["mra"])
    , ("marce", ["ma'e"])
    , ("marde", ["mad"])
    , ("margu", ["mag"])
    , ("marji", ["mai", "maj"])
    , ("marxa", ["max"])
    , ("masno", ["sno"])
    , ("masti", ["ma'i"])
    , ("mavji", ["mav"])
    , ("maxri", ["xri"])
    , ("mebri", ["meb"])
    , ("megdo", ["meg"])
    , ("mei",   ["mei", "mem"])
    , ("mekso", ["me'o", "mek"])
    , ("melbi", ["mel", "mle"])
    , ("meljo", ["mej"])
    , ("menli", ["men"])
    , ("mensi", ["me'i", "mes"])
    , ("mentu", ["me'u", "met"])
    , ("merko", ["mer"])
    , ("merli", ["mre"])
    , ("mexno", ["mex"])
    , ("mi",    ["mib"])
    , ("midju", ["mij"])
    , ("mifra", ["mif"])
    , ("mikce", ["mic"])
    , ("mikri", ["mik"])
    , ("milti", ["mil"])
    , ("milxe", ["mli"])
    , ("minde", ["mi'e", "mid"])
    , ("minji", ["mi'i"])
    , ("minra", ["mir"])
    , ("mintu", ["mi'u", "mit"])
    , ("mipri", ["mip"])
    , ("misno", ["mi'o", "mis"])
    , ("mitre", ["tre"])
    , ("mixre", ["mix", "xre"])
    , ("mlana", ["mla"])
    , ("mlatu", ["lat"])
    , ("mleca", ["me'a", "mec"])
    , ("mledi", ["led"])
    , ("mluni", ["lun"])
    , ("mo'a",  ["mob"])
    , ("mo'i",  ["mov"])
    , ("moi",   ["moi", "mom"])
    , ("mokca", ["moc"])
    , ("moklu", ["mo'u", "mol"])
    , ("molki", ["mlo"])
    , ("molro", ["mo'o"])
    , ("morji", ["mo'i", "moj"])
    , ("morko", ["mor"])
    , ("morna", ["mo'a", "mon"])
    , ("morsi", ["mro"])
    , ("mosra", ["mos"])
    , ("mrilu", ["mri"])
    , ("mruli", ["mru"])
    , ("mu",    ["mum"])
    , ("mu'e",  ["muf"])
    , ("mucti", ["mut"])
    , ("mudri", ["mud"])
    , ("mukti", ["mu'i", "muk"])
    , ("mulno", ["mu'o", "mul"])
    , ("munje", ["mu'e", "muj"])
    , ("mupli", ["mup"])
    , ("murta", ["mu'a", "mur"])
    , ("muslo", ["mus"])
    , ("mutce", ["tce"])
    , ("muvdu", ["mu'u", "muv"])
    , ("muzga", ["muz"])
    , ("na",    ["nar"])
    , ("na'e",  ["nal"])
    , ("nabmi", ["nam"])
    , ("nakni", ["nak"])
    , ("nalci", ["na'i"])
    , ("namcu", ["na'u", "nac"])
    , ("nanba", ["nab"])
    , ("nanca", ["na'a"])
    , ("nandu", ["nad"])
    , ("nanmu", ["nau"])
    , ("nanvi", ["nav"])
    , ("narge", ["nag"])
    , ("narju", ["naj"])
    , ("natfe", ["na'e", "naf"])
    , ("natmi", ["nai", "nat"])
    , ("naxle", ["nax", "xle"])
    , ("nazbi", ["naz", "zbi"])
    , ("nejni", ["nen"])
    , ("nelci", ["nei", "nel"])
    , ("nenri", ["ne'i", "ner"])
    , ("ni",    ["nil"])
    , ("nibli", ["ni'i", "nib"])
    , ("nicte", ["cte"])
    , ("nikle", ["nik"])
    , ("nilce", ["ni'e"])
    , ("ninmu", ["ni'u", "nim"])
    , ("nirna", ["nir"])
    , ("nitcu", ["tcu"])
    , ("nivji", ["niv"])
    , ("nixli", ["nix", "xli"])
    , ("no",    ["non"])
    , ("no'e",  ["no'e", "nor"])
    , ("nobli", ["no'i", "nol"])
    , ("notci", ["noi", "not"])
    , ("nu",    ["nun"])
    , ("nu'o",  ["nu'o"])
    , ("nukni", ["nuk"])
    , ("nupre", ["nu'e", "nup"])
    , ("nurma", ["num"])
    , ("nutli", ["nu'i", "nul"])
    , ("nuzba", ["nuz"])
    , ("pa",    ["pav"])
    , ("pacna", ["pa'a"])
    , ("pagbu", ["pag", "pau"])
    , ("pagre", ["gre"])
    , ("pajni", ["pai"])
    , ("palci", ["pac"])
    , ("palku", ["pak"])
    , ("panci", ["pan"])
    , ("pandi", ["pad"])
    , ("panlo", ["pa'o"])
    , ("panpi", ["pap"])
    , ("pante", ["pat"])
    , ("panzi", ["paz"])
    , ("parbi", ["pab"])
    , ("pastu", ["pas"])
    , ("patfu", ["pa'u", "paf"])
    , ("patxu", ["pax"])
    , ("pe'a",  ["pev"])
    , ("pelji", ["ple"])
    , ("pelxu", ["pel"])
    , ("pemci", ["pem"])
    , ("penbi", ["peb"])
    , ("pencu", ["pe'u", "pec"])
    , ("pendo", ["pe'o", "ped"])
    , ("penmi", ["pe'i", "pen"])
    , ("pensi", ["pei", "pes"])
    , ("perli", ["per"])
    , ("pesxu", ["pex"])
    , ("petso", ["pet"])
    , ("pezli", ["pez"])
    , ("pi",    ["piz"])
    , ("pi'u",  ["piv"])
    , ("picti", ["pic"])
    , ("pilji", ["pi'i"])
    , ("pilka", ["pi'a", "pil"])
    , ("pilno", ["pli"])
    , ("pimlu", ["pi'u", "pim"])
    , ("pindi", ["pid"])
    , ("pinfu", ["pif"])
    , ("pinka", ["pik"])
    , ("pinsi", ["pis"])
    , ("pinta", ["pin"])
    , ("pinxe", ["pix"])
    , ("pipno", ["pi'o"])
    , ("pixra", ["pir", "xra"])
    , ("platu", ["pla"])
    , ("pleji", ["le'i", "lej"])
    , ("plibu", ["pib"])
    , ("plipe", ["pi'e", "pip"])
    , ("plita", ["pit"])
    , ("plixa", ["lix"])
    , ("pluja", ["luj"])
    , ("pluka", ["pu'a", "puk"])
    , ("pluta", ["lu'a", "lut"])
    , ("polje", ["plo"])
    , ("polno", ["pol"])
    , ("ponjo", ["po'o", "pon"])
    , ("ponse", ["po'e", "pos"])
    , ("porpi", ["po'i", "pop"])
    , ("porsi", ["poi", "por"])
    , ("porto", ["pot"])
    , ("prali", ["pal"])
    , ("prami", ["pa'i", "pam"])
    , ("prane", ["pa'e"])
    , ("preja", ["pe'a", "pej"])
    , ("prenu", ["pre"])
    , ("preti", ["rei", "ret"])
    , ("prije", ["pij"])
    , ("prina", ["pri"])
    , ("prosa", ["ro'a", "ros"])
    , ("pruce", ["ru'e", "ruc"])
    , ("pruni", ["pun"])
    , ("pruxi", ["ru'i", "rux"])
    , ("pu'i",  ["pus"])
    , ("pu'u",  ["puv"])
    , ("pulce", ["pu'e", "puc"])
    , ("punji", ["pu'i", "puj"])
    , ("punli", ["pul"])
    , ("purci", ["pru", "pur"])
    , ("purdi", ["pud"])
    , ("purmo", ["pu'o", "pum"])
    , ("radno", ["ra'o"])
    , ("rafsi", ["raf"])
    , ("ragve", ["rav"])
    , ("raktu", ["ra'u"])
    , ("ralci", ["rac"])
    , ("ralju", ["ral"])
    , ("ralte", ["ra'e"])
    , ("randa", ["rad"])
    , ("rango", ["rag"])
    , ("ranji", ["ra'i"])
    , ("ranmi", ["ram"])
    , ("ranti", ["ran"])
    , ("ranxi", ["rax"])
    , ("rapli", ["rap"])
    , ("rarna", ["rar"])
    , ("ratni", ["rat"])
    , ("re",    ["rel"])
    , ("rebla", ["reb"])
    , ("rectu", ["re'u", "rec"])
    , ("remna", ["re'a", "rem"])
    , ("renro", ["re'o", "rer"])
    , ("renvi", ["re'i", "rev"])
    , ("respa", ["res"])
    , ("ricfu", ["cfu", "rif"])
    , ("rigni", ["rig"])
    , ("rijno", ["rij"])
    , ("rilti", ["ril"])
    , ("rimni", ["rim"])
    , ("rinju", ["ri'u"])
    , ("rinka", ["ri'a", "rik"])
    , ("rirni", ["rir"])
    , ("rirxe", ["ri'e"])
    , ("rismi", ["ris"])
    , ("ritli", ["ri'i"])
    , ("rivbi", ["riv"])
    , ("ro",    ["rol"])
    , ("roi",   ["roi", "rom"])
    , ("rokci", ["ro'i", "rok"])
    , ("romge", ["rog"])
    , ("ropno", ["ro'o", "ron"])
    , ("rorci", ["ror"])
    , ("rotsu", ["ro'u", "rot", "tsu"])
    , ("rozgu", ["roz", "zgu"])
    , ("ruble", ["ble", "rub"])
    , ("rufsu", ["ruf"])
    , ("runme", ["rum"])
    , ("rupnu", ["ru'u", "rup"])
    , ("rusko", ["ru'o", "ruk"])
    , ("rutni", ["run"])
    , ("sabji", ["sab"])
    , ("sadjo", ["djo"])
    , ("sakci", ["sak"])
    , ("sakli", ["sal"])
    , ("sakta", ["sat"])
    , ("salci", ["sla"])
    , ("salpo", ["sa'o"])
    , ("sampu", ["sap"])
    , ("sance", ["sna"])
    , ("sanga", ["sa'a", "sag"])
    , ("sanji", ["saj"])
    , ("sanli", ["sa'i"])
    , ("sanmi", ["sai"])
    , ("sarcu", ["sa'u"])
    , ("sarji", ["sra"])
    , ("sarxe", ["sax"])
    , ("saske", ["ske"])
    , ("satre", ["sa'e"])
    , ("savru", ["sav", "vru"])
    , ("sazri", ["saz"])
    , ("se",    ["sel"])
    , ("sefta", ["sfe"])
    , ("selci", ["sle"])
    , ("selfu", ["se'u", "sef"])
    , ("semto", ["sme"])
    , ("senci", ["sec"])
    , ("senpi", ["sen"])
    , ("senta", ["set"])
    , ("senva", ["sev", "sne"])
    , ("sepli", ["sei", "sep"])
    , ("serti", ["ser"])
    , ("setca", ["se'a"])
    , ("sevzi", ["se'i", "sez"])
    , ("sfasa", ["sfa"])
    , ("sfofa", ["sfo"])
    , ("sfubu", ["su'u", "sub"])
    , ("si'o",  ["siz"])
    , ("siclu", ["sil"])
    , ("sicni", ["si'i"])
    , ("sidbo", ["si'o", "sib"])
    , ("sidju", ["dju"])
    , ("sigja", ["sig"])
    , ("silka", ["sik"])
    , ("simlu", ["mlu"])
    , ("simsa", ["smi"])
    , ("simxu", ["si'u", "sim"])
    , ("sinma", ["si'a"])
    , ("sinxa", ["sni"])
    , ("sipna", ["sip"])
    , ("sirji", ["sir"])
    , ("sirxo", ["six"])
    , ("sisku", ["sis"])
    , ("sisti", ["sti"])
    , ("sitna", ["sit"])
    , ("sivni", ["siv"])
    , ("skami", ["sam"])
    , ("skapi", ["kap"])
    , ("skari", ["ska"])
    , ("skicu", ["ski"])
    , ("skiji", ["sij"])
    , ("skina", ["kin"])
    , ("skori", ["sko"])
    , ("skoto", ["ko'o", "kot"])
    , ("skuro", ["ku'o"])
    , ("slabu", ["sau"])
    , ("slari", ["sar"])
    , ("slasi", ["las"])
    , ("sligu", ["lig"])
    , ("slilu", ["sli"])
    , ("slovo", ["lo'o", "lov"])
    , ("sluji", ["slu"])
    , ("smaji", ["sma"])
    , ("smoka", ["smo"])
    , ("smuci", ["muc"])
    , ("smuni", ["mun", "smu"])
    , ("snada", ["sad"])
    , ("snanu", ["nan"])
    , ("snidu", ["nid"])
    , ("snime", ["si'e"])
    , ("snipa", ["nip"])
    , ("snuji", ["nuj"])
    , ("snura", ["nu'a", "nur"])
    , ("snuti", ["nut"])
    , ("so",    ["soz"])
    , ("so'a",  ["soj"])
    , ("so'e",  ["sop"])
    , ("so'i",  ["so'i", "sor"])
    , ("so'o",  ["sos"])
    , ("so'u",  ["sot"])
    , ("sobde", ["so'e", "sob"])
    , ("sodva", ["sod"])
    , ("softo", ["sof"])
    , ("solji", ["slo"])
    , ("solri", ["sol"])
    , ("sombo", ["so'o", "som"])
    , ("sonci", ["soi", "son"])
    , ("sorcu", ["soc", "sro"])
    , ("sorgu", ["sog"])
    , ("sovda", ["so'a", "sov"])
    , ("spaji", ["paj"])
    , ("spano", ["san"])
    , ("spati", ["spa"])
    , ("speni", ["spe"])
    , ("spisa", ["spi"])
    , ("spofu", ["po'u", "pof"])
    , ("spoja", ["po'a", "poj"])
    , ("spuda", ["spu"])
    , ("sputu", ["pu'u", "put"])
    , ("sraji", ["raj"])
    , ("sraku", ["rak"])
    , ("srana", ["ra'a"])
    , ("srasu", ["sas"])
    , ("srera", ["sre"])
    , ("sruma", ["ru'a"])
    , ("sruri", ["rur", "sru"])
    , ("stace", ["sac"])
    , ("staku", ["tak"])
    , ("stali", ["sta"])
    , ("stapa", ["tap"])
    , ("steba", ["seb"])
    , ("steci", ["te'i", "tec"])
    , ("stedu", ["sed"])
    , ("stela", ["tel"])
    , ("stero", ["te'o"])
    , ("stici", ["sic"])
    , ("stidi", ["sid", "ti'i"])
    , ("stika", ["tik"])
    , ("stizu", ["tiz"])
    , ("stodi", ["sto"])
    , ("stuna", ["sun"])
    , ("stura", ["su'a", "tur"])
    , ("stuzi", ["stu", "tuz"])
    , ("su'e",  ["su'e", "sup"])
    , ("su'o",  ["su'o", "suz"])
    , ("su'u",  ["suv"])
    , ("sucta", ["suc"])
    , ("sudga", ["sud"])
    , ("sufti", ["sfu"])
    , ("suksa", ["suk"])
    , ("sumji", ["suj"])
    , ("sumti", ["su'i", "sum"])
    , ("sunga", ["sug"])
    , ("sunla", ["sul"])
    , ("surla", ["sur"])
    , ("sutra", ["sut"])
    , ("ta",    ["taz"])
    , ("tabno", ["tab"])
    , ("tadni", ["tad"])
    , ("tagji", ["tag"])
    , ("talsa", ["tal"])
    , ("tamji", ["taj"])
    , ("tanbo", ["ta'o"])
    , ("tance", ["tac"])
    , ("tanru", ["tau"])
    , ("tansi", ["tas"])
    , ("tanxe", ["ta'e", "tax"])
    , ("tarci", ["tar"])
    , ("tarmi", ["tai", "tam"])
    , ("tarti", ["tra"])
    , ("tatpi", ["ta'i"])
    , ("tatru", ["tat"])
    , ("tavla", ["ta'a", "tav"])
    , ("taxfu", ["ta'u", "taf"])
    , ("tcaci", ["cac"])
    , ("tcadu", ["tca"])
    , ("tcena", ["ten"])
    , ("tcica", ["tic"])
    , ("tcidu", ["tid"])
    , ("tcila", ["til"])
    , ("tcima", ["ti'a", "tim"])
    , ("te",    ["ter"])
    , ("temci", ["tei", "tem"])
    , ("tenfa", ["tef"])
    , ("tengu", ["te'u", "teg"])
    , ("terdi", ["ted"])
    , ("terpa", ["te'a", "tep"])
    , ("terto", ["tet"])
    , ("ti",    ["tif"])
    , ("tigni", ["tig"])
    , ("tikpa", ["tip"])
    , ("tilju", ["tij"])
    , ("tinbe", ["tib"])
    , ("tirna", ["tin"])
    , ("tirse", ["tir"])
    , ("tisna", ["tis"])
    , ("titla", ["tit"])
    , ("tivni", ["tiv"])
    , ("tixnu", ["ti'u", "tix"])
    , ("to'e",  ["to'e", "tol"])
    , ("toknu", ["tok"])
    , ("toldi", ["tod"])
    , ("tonga", ["to'a", "tog"])
    , ("tordu", ["to'u", "tor"])
    , ("torni", ["to'i", "ton"])
    , ("traji", ["rai"])
    , ("trene", ["re'e", "ren"])
    , ("tricu", ["ric"])
    , ("trina", ["tri"])
    , ("trixe", ["rix", "ti'e"])
    , ("troci", ["toc", "toi"])
    , ("tsali", ["tsa"])
    , ("tsani", ["tan"])
    , ("tsiju", ["tsi"])
    , ("tsina", ["sin"])
    , ("tu",    ["tuf"])
    , ("tubnu", ["tu'u"])
    , ("tugni", ["tu'i", "tug"])
    , ("tujli", ["tuj"])
    , ("tumla", ["tu'a", "tum"])
    , ("tunba", ["tub"])
    , ("tunka", ["tuk"])
    , ("tunlo", ["tu'o", "tul"])
    , ("tunta", ["tun"])
    , ("tuple", ["tu'e", "tup"])
    , ("turni", ["tru"])
    , ("tutci", ["tci"])
    , ("tutra", ["tut"])
    , ("va",    ["vaz"])
    , ("vacri", ["var"])
    , ("vajni", ["vai", "vaj"])
    , ("valsi", ["val", "vla"])
    , ("vamji", ["va'i", "vam"])
    , ("vamtu", ["vat"])
    , ("vanbi", ["vab"])
    , ("vanci", ["vac"])
    , ("vanju", ["van"])
    , ("vasru", ["vas", "vau"])
    , ("vasxu", ["va'u", "vax"])
    , ("ve",    ["vel"])
    , ("ve'e",  ["ve'e"])
    , ("vecnu", ["ve'u", "ven"])
    , ("venfu", ["vef"])
    , ("vensa", ["ves"])
    , ("verba", ["ve'a", "ver"])
    , ("vi",    ["viz"])
    , ("vibna", ["vib"])
    , ("vidru", ["vir"])
    , ("vifne", ["vif"])
    , ("vikmi", ["vi'i", "vim"])
    , ("viknu", ["vik"])
    , ("vimcu", ["vi'u", "vic"])
    , ("vindu", ["vid"])
    , ("vinji", ["vij"])
    , ("vipsi", ["vip"])
    , ("virnu", ["vri"])
    , ("viska", ["vi'a", "vis"])
    , ("vitci", ["vit"])
    , ("vitke", ["vi'e"])
    , ("vitno", ["vi'o"])
    , ("vlagi", ["lag"])
    , ("vlile", ["vil"])
    , ("vlipa", ["vli"])
    , ("vo",    ["von"])
    , ("vofli", ["voi", "vol"])
    , ("voksa", ["vo'a", "vok"])
    , ("vorme", ["vor", "vro"])
    , ("vraga", ["vra"])
    , ("vreji", ["rej", "vei"])
    , ("vreta", ["vre"])
    , ("vrude", ["vu'e", "vud"])
    , ("vrusi", ["vu'i", "vus"])
    , ("vu",    ["vuz"])
    , ("vukro", ["vu'o", "vur"])
    , ("xa",    ["xav"])
    , ("xabju", ["xa'u"])
    , ("xadba", ["xab"])
    , ("xadni", ["xad"])
    , ("xajmi", ["xam"])
    , ("xaksu", ["xak"])
    , ("xalka", ["xal"])
    , ("xamgu", ["xag", "xau"])
    , ("xampo", ["xa'o", "xap"])
    , ("xamsi", ["xas"])
    , ("xance", ["xa'e", "xan"])
    , ("xanri", ["xar"])
    , ("xarci", ["xa'i", "xac"])
    , ("xarju", ["xaj"])
    , ("xatra", ["xa'a"])
    , ("xatsi", ["xat"])
    , ("xazdo", ["xaz", "zdo"])
    , ("xe",    ["xel"])
    , ("xebni", ["xei", "xen"])
    , ("xebro", ["bro", "xeb"])
    , ("xecto", ["cto", "xet"])
    , ("xedja", ["xe'a", "xej"])
    , ("xekri", ["xe'i", "xek"])
    , ("xelso", ["xes"])
    , ("xendo", ["xe'o", "xed"])
    , ("xenru", ["xe'u", "xer"])
    , ("xexso", ["xex"])
    , ("xindo", ["xin"])
    , ("xinmo", ["xim"])
    , ("xirma", ["xi'a", "xir"])
    , ("xislu", ["xi'u", "xil"])
    , ("xispo", ["xip"])
    , ("xlali", ["xla"])
    , ("xlura", ["xlu"])
    , ("xotli", ["xoi", "xol"])
    , ("xrabo", ["rab"])
    , ("xrani", ["xai"])
    , ("xriso", ["xi'o", "xis"])
    , ("xruba", ["xub"])
    , ("xruki", ["xuk"])
    , ("xrula", ["rul"])
    , ("xruti", ["xru"])
    , ("xukmi", ["xu'i", "xum"])
    , ("xunre", ["xu'e", "xun"])
    , ("xurdo", ["xu'o", "xur"])
    , ("xusra", ["xu'a", "xus"])
    , ("xutla", ["xul"])
    , ("za'i",  ["zaz"])
    , ("za'o",  ["za'o"])
    , ("zabna", ["za'a", "zan"])
    , ("zajba", ["zaj"])
    , ("zalvi", ["zal"])
    , ("zanru", ["zar", "zau"])
    , ("zarci", ["zac", "zai"])
    , ("zargu", ["za'u", "zag"])
    , ("zasni", ["zas"])
    , ("zasti", ["za'i", "zat"])
    , ("zbabu", ["bab"])
    , ("zbasu", ["zba"])
    , ("zbepi", ["zbe"])
    , ("zdani", ["zda"])
    , ("zdile", ["zdi"])
    , ("ze",    ["zel"])
    , ("ze'e",  ["ze'e"])
    , ("ze'o",  ["ze'o", "zev"])
    , ("zekri", ["zei", "zer"])
    , ("zenba", ["ze'a", "zen"])
    , ("zepti", ["zep"])
    , ("zetro", ["zet"])
    , ("zgana", ["zga"])
    , ("zgike", ["gi'e", "zgi"])
    , ("zifre", ["zi'e", "zif"])
    , ("zinki", ["zi'i", "zin"])
    , ("zirpu", ["zi'u", "zir"])
    , ("zivle", ["vle", "ziv"])
    , ("zmadu", ["mau", "zma"])
    , ("zmiku", ["zmi"])
    , ("zo'a",  ["zo'a", "zon"])
    , ("zo'i",  ["zo'i", "zor"])
    , ("zu'o",  ["zum"])
    , ("zukte", ["zu'e", "zuk"])
    , ("zumri", ["zmu"])
    , ("zungi", ["zug"])
    , ("zunle", ["zul"])
    , ("zunti", ["zu'i", "zun"])
    , ("zutse", ["tse", "zut"])
    , ("zvati", ["zva"])
    ]
